class Images {
  const Images();
  static final home = "assets/images/home.svg";
  static final user = "assets/images/user.svg";
  static final document = "assets/images/document.svg";
  static final initialAvater = "assets/images/initial_avater_icon.svg";
  static final initial_group = "assets/images/initial_group_icon.svg";
  static final shoppingCart = "assets/images/shopping-cart.svg";
  static final welcome_screen_img = "assets/images/welcome_screen_img.png";
  static final food_yours_logo = "assets/images/food_yours_logo.svg";
  static final splash_screen_bg_img = "assets/images/splash_screen_bg_img.png";
  static final registration_pattern_design =
      "assets/images/registration_pattern_design.svg";
  static final food_category = "assets/images/food_category.png";
  static final popular_chef = "assets/images/popular_chef.png";
  static final ad_banner = "assets/images/ad_banner.svg";
  static final large_order_banner = "assets/images/large_order_banner.png";
  static final warning_symbol = "assets/images/warning_symbol.svg";
  static final notification_symbol = "assets/images/notification_symbol.svg";
  static final settings = "assets/images/settings.svg";
  static final search_result = "assets/images/search_result.png";
  static final chef = "assets/images/chef.png";
  static final back = "assets/images/back.svg";
  static final cart = "assets/images/cart.svg";
  static final chef_bg_image = "assets/images/chef_bg_image.jpg";
  static final minus_circle = "assets/images/minus_circle.svg";
  static final plus_circle = "assets/images/plus_circle.svg";
  static final anonymous_chef_reviewer =
      "assets/images/anonymous_chef_reviewer.svg";
  static final success_check = "assets/images/success_check.svg";
  static final qr_image = "assets/images/qr_image.png";
  static final qr_overlay = "assets/images/qr_overlay.png";
  static final alert_success_check = "assets/images/alert_success_check.svg";
  static final female_chef = "assets/images/female_chef.jpg";
  static final calender = "assets/images/calender.svg";
  static final pay_stack = "assets/images/pay_stack.png";
  static final pen = "assets/images/pen.svg";
  static final whatsapp = "assets/images/whatsapp.svg";
  static final facebook = "assets/images/facebook.svg";
  static final instagram = "assets/images/instagram.svg";
  static final twitter = "assets/images/twitter.svg";
  static final copy = "assets/images/copy.svg";
  static final eye_off = "assets/images/eye_off.svg";
  static final pen_2 = "assets/images/pen_2.svg";
  static final question_mark = "assets/images/question_mark.svg";
  static final head_phone = "assets/images/head_phone.svg";
  static final question = "assets/images/question.svg";
  static final clarity_list = "assets/images/clarity_list.svg";
  static final document_2 = "assets/images/document_2.svg";
  static final male_chef = "assets/images/male_chef.png";
  static final courier = "assets/images/courier.jpg";
  static final eye_on = "assets/images/eye_on.svg";
  static final card_chip = "assets/images/card_chip.svg";
  static final loading = "assets/images/loading.gif";
  static final ng = "assets/images/ng.png";
  static final chef_place_holder = "assets/images/place_holder.jpg";
  static final star = "assets/images/star.svg";
  static final female_chef_placeholder =
      "assets/images/female_chef_placeholder.png";
}
